include: package:lint/analysis_options.yaml

analyzer:
  #Exclude the file borrowed from flutter sdk
  exclude:
    - lib/utils/widgets/bottom_sheet_route.dart
    - lib/**/*.gr.dart
    - lib/**/*.g.dart
    - test/**/*.mocks.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gql.g.dart

  errors:
    # reasonable fpr no-sound-null-safety project
    import_of_legacy_library_into_null_safe: ignore

linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: false

    # Prefer using lowerCamelCase for constant names
    constant_identifier_names: false

    prefer_const_constructors: true

    prefer_const_literals_to_create_immutables: false

    # Turn off sort dependencies
    sort_pub_dependencies: false
